/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javatutorial;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
//    	Thread t = new Thread(new MyThread());
//    	t.setDaemon(true);
//		t.start();
		System.out.println("back in the main");
    }
}
